### ISSUE TITLE
オプションについて

### ISSUE THREAD

**Issue by rsk0315** [monkukui/ggg#3]
言いがかりかもしれないんですが、

```
-f, --format     graph format is normal (default true)
```

というのは不親切な気がしてて、normal というのが何を表すのかよくわからない気がします。

default で true と言われても false にする方法が非自明じゃないですか？（シェルとかだと `+f` とかを `-f` の否定として使いそうですが）
いろいろ試して方法はわかったんですが、`-f` のような短いオプションの引数は `-f=false` ではなく `-f false` とするのが妥当だと思います（`=` を使うのは直感に反する）

true/false のオプションであれば、「指定なし：false」「指定あり：true」が一番直感的な気がします。

今回は、format であり、2 値とは限らないので、

```
-f, --format=FMT     graph format (FMT is one of: adjmatrix, adjlist). Default: adjlist.
```

みたいな形式の方が直感的な気がします（各フォーマットの名前については再考の余地があるかもです）

**Comment by rsk0315** [comment]
同様に、`--indexed=1` とか `--indexed=0` の方がよさそうです。
あるいは `-0` や `-1` でもいいかもしれません？

**Comment by rsk0315** [comment]
たぶんそのうち対応されたら治ると思うんですが、

```
ggg -format=false
```

を実行すると、なぜか Finder が開いちゃうね

**Comment by monkukui** [comment]
>いろいろ試して方法はわかったんですが、-f のような短いオプションの引数は -f=false ではなく -f false とするのが妥当だと思います（= を使うのは直感に反する）

Go では、`boolean` のフラグを扱う場合、`-f false` と書くことができないです（たぶん）

`-f=true` とするか、単に`-f` とします。
default を `true` にしていると、`false` にしたいとき `-f=false` と書く以外に方法がない気がします。

https://golang.org/pkg/flag/


なので、色々悩ましいです。
